# Generated by Django 4.2.17 on 2024-12-07 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_pago_paypalconfig_alter_compra_compra_importe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalconfig',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paypalconfig',
            name='account_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paypalconfig',
            name='mode',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], max_length=10),
        ),
    ]
