# Generated by Django 4.2.17 on 2024-12-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_paypalconfig_cliente_alter_paypalconfig_account_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paypalconfig',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='paypalconfig',
            name='client_secret',
        ),
        migrations.AlterField(
            model_name='paypalconfig',
            name='account_name',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paypalconfig',
            name='mode',
            field=models.CharField(choices=[('sandbox', 'Sandbox'), ('live', 'Live')], default='sandbox', max_length=10),
        ),
    ]
