# Generated by Django 4.2.17 on 2024-12-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0004_remove_paypalconfig_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cliente_saldo',
        ),
    ]
