# Generated by Django 4.2.17 on 2024-12-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0005_remove_cliente_cliente_saldo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard')], max_length=50)),
                ('numero_cuenta', models.CharField(max_length=16, unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nombre_cuenta', models.CharField(blank=True, max_length=100, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='tienda.cliente')),
            ],
        ),
        migrations.RemoveField(
            model_name='paypalconfig',
            name='cliente',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='PayPalConfig',
        ),
    ]
