# Generated by Django 4.2.17 on 2024-12-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0006_cuentapago_remove_paypalconfig_cliente_delete_pago_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard')], default='visa', max_length=20),
        ),
    ]
