# Generated by Django 4.2.17 on 2024-12-08 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_comentario_respuesta_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='producto_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='tienda.producto_compra'),
        ),
    ]
