# Generated by Django 4.2.21 on 2025-05-11 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_alter_comentario_producto_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuentapago',
            name='numero_cuenta',
        ),
        migrations.RemoveField(
            model_name='cuentapago',
            name='saldo',
        ),
        migrations.RemoveField(
            model_name='cuentapago',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cuentapago',
            name='email_paypal',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='metodo_pago',
            field=models.CharField(default='paypal', editable=False, max_length=20),
        ),
    ]
