# Generated by Django 4.2.21 on 2025-05-30 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_remove_cuentapago_numero_cuenta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direccion',
            name='tipo',
        ),
    ]
