# Generated by Django 4.2.21 on 2025-05-31 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0011_remove_direccion_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='producto_vip',
        ),
    ]
