# Generated by Django 4.2.21 on 2025-06-01 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_remove_producto_producto_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='respuesta_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='tienda.comentario'),
        ),
    ]
